# Generated by Django 6.0.5 on 2026-05-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='firma',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Digital'),
        ),
    ]
