# Generated by Django 6.0.5 on 2026-05-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_transaction_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='item',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.persona', verbose_name='Responsable'),
        ),
    ]
