# Generated by Django 6.0.5 on 2026-05-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_item_area_item_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='codigo_patrimonial',
        ),
        migrations.AddField(
            model_name='item',
            name='responsable_otro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de responsable (Otro)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='responsable_otro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de responsable (Otro)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('PC', 'PC'), ('Impresora', 'Impresora'), ('Notebook', 'Notebook'), ('Redes', 'Redes'), ('Otro', 'Otro')], default='Hardware', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.persona', verbose_name='Responsable'),
        ),
    ]
