# Generated by Django 6.0.5 on 2026-05-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_transaction_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ip', models.GenericIPAddressField(unique=True, verbose_name='Dirección IP')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción / Equipo')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('RESERVADA', 'Reservada')], default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips', to='inventario.area', verbose_name='Área Asignada')),
            ],
            options={
                'verbose_name': 'Dirección IP',
                'verbose_name_plural': 'Direcciones IP',
                'ordering': ['direccion_ip'],
            },
        ),
    ]
