# Generated by Django 6.0.5 on 2026-05-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ips', '0001_initial'),
        ('inventario', '0003_item_area_item_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionip',
            name='dispositivo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_asignada', to='inventario.item', verbose_name='Dispositivo / Máquina Asignada'),
        ),
    ]
